In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
my_array = np.array([1,2,3,4,5])

In [4]:
my_list = [1,2,3,4,5]

In [5]:
my_list[0]

1

In [6]:
my_array[0]

1

In [7]:
list_of_lists = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [8]:
list_of_lists[1][1]

5

In [9]:
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [10]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
matrix[1,1]

5

In [13]:
my_list[1:]

[2, 3, 4, 5]

In [14]:
my_array[1:]

array([2, 3, 4, 5])

In [15]:
matrix[1:, :2]

array([[4, 5],
       [7, 8]])

In [16]:
my_array

array([1, 2, 3, 4, 5])

In [17]:
mask = [False, True, False, True, False]

my_array[mask]

array([2, 4])

In [18]:
my_array >2

array([False, False,  True,  True,  True])

In [19]:
my_array[my_array > 2]

array([3, 4, 5])

In [20]:
my_array[my_array % 2 == 0]

array([2, 4])

In [21]:
my_array % 2

array([1, 0, 1, 0, 1])

In [22]:
my_array % 2 == 0

array([False,  True, False,  True, False])

In [25]:
my_array[my_array % 2 == 0]

array([2, 4])

In [26]:
new_array = my_array[my_array % 2 == 0]

In [27]:
new_array[new_array > 2]

array([4])

In [61]:
mask = (my_array % 2 == 0) | (my_array > 2)
my_array[mask]

array([2, 3, 4, 5])

In [28]:
np.random.randn(10)

array([ 0.04795075, -0.09580922,  0.95174144,  0.3087097 , -0.23627758,
       -0.49356216, -1.08926153, -1.28461428,  0.07637892, -1.11361657])

In [29]:
np.random.randn(4, 4)

array([[-0.35756458, -0.46079028, -1.71853332,  0.88265418],
       [-0.67240501, -1.84933208, -0.48579584, -1.37503778],
       [ 0.77897616,  0.37314278, -0.70173098, -0.25118593],
       [-0.28875316, -0.31665449, -0.77102961,  1.12484636]])

In [30]:
np.random.randn(2, 2, 2)

array([[[-1.25769019,  0.74102932],
        [ 0.53332251,  1.15988289]],

       [[-0.80978588,  0.41690956],
        [ 0.4187396 ,  0.69516887]]])

In [31]:
np.random.randn(2, 2, 2, 2)

array([[[[ 0.39798278, -0.11183711],
         [-0.19906813,  0.21319723]],

        [[-0.87258846, -1.22693579],
         [ 0.79293057, -0.91403247]]],


       [[[-0.1138883 , -0.14389699],
         [-0.1478411 , -0.50504301]],

        [[-0.77125452, -1.53126092],
         [-0.69708328,  0.78071138]]]])

In [35]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.full(3, 15)

array([15, 15, 15])

In [41]:
np.full((3, 3), 15)

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

In [48]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [51]:
np.linspace(1, 4, 5) #(min, max, /by)
# from 1-4 divided by 5

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [54]:
my_array.min()

1

In [55]:
my_array.max()

5

In [56]:
my_array.sum()

15

In [57]:
my_array.std()

1.4142135623730951

In [60]:
matrix.mean()

5.0